
env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

extends: airbnb-base

settings:
  react:
    version: '17'
